import React from "react";
import { Button } from "@/components/ui/button";
import { Download, FileText, Printer, Share2, Image } from "lucide-react";
import { jsPDF } from "jspdf";
import { useToast } from "@/hooks/use-toast";

interface ExportProps {
  elementId: string;
  title: string;
  data?: any;
}

export function ExportToPDFButton({ elementId, title }: ExportProps) {
  const { toast } = useToast();

  const handleExport = async () => {
    try {
      const element = document.getElementById(elementId);
      if (!element) {
        toast({ title: "Export Failed", description: "Could not find the content to export.", variant: "destructive" });
        return;
      }

      const doc = new jsPDF("p", "mm", "a4");
      const pageWidth = doc.internal.pageSize.getWidth();

      try {
        const html2canvas = (await import("html2canvas")).default;
        const canvas = await html2canvas(element, {
          backgroundColor: "#ffffff",
          scale: 2,
          useCORS: true,
          logging: false,
          allowTaint: true,
          removeContainer: true,
        });
        const imgData = canvas.toDataURL("image/png");
        const imgWidth = pageWidth - 20;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text(title, 10, 12);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.text("RealProfits.com", 10, 18);
        doc.addImage(imgData, "PNG", 10, 22, imgWidth, Math.min(imgHeight, 260));
      } catch {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18);
        doc.text(title, 10, 20);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.text("Generated by RealProfits.com", 10, 28);
        doc.setDrawColor(200);
        doc.line(10, 32, pageWidth - 10, 32);

        const textContent = element.innerText || element.textContent || "";
        const lines = doc.splitTextToSize(textContent, pageWidth - 20);
        doc.setFontSize(9);
        let y = 38;
        for (const line of lines) {
          if (y > 280) {
            doc.addPage();
            y = 15;
          }
          doc.text(line, 10, y);
          y += 5;
        }
      }

      doc.save(`${title.replace(/\s+/g, '-').toLowerCase()}-results.pdf`);
      toast({ title: "PDF Downloaded", description: "Your results have been saved as a PDF." });
    } catch (err) {
      console.error("PDF export error:", err);
      toast({ title: "Export Failed", description: "Could not generate PDF.", variant: "destructive" });
    }
  };

  return (
    <Button variant="outline" size="sm" onClick={handleExport} className="flex items-center gap-2">
      <FileText className="w-4 h-4" /> PDF
    </Button>
  );
}

export function DownloadPNGButton({ elementId, title }: ExportProps) {
  const { toast } = useToast();

  const handleExport = async () => {
    try {
      const element = document.getElementById(elementId);
      if (!element) {
        toast({ title: "Export Failed", description: "Could not find the content.", variant: "destructive" });
        return;
      }

      const html2canvas = (await import("html2canvas")).default;
      const canvas = await html2canvas(element, {
        backgroundColor: "#ffffff",
        scale: 2,
        useCORS: true,
        logging: false,
        allowTaint: true,
        removeContainer: true,
      });
      const link = document.createElement("a");
      link.download = `${title.replace(/\s+/g, '-').toLowerCase()}-results.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
      toast({ title: "Image Downloaded", description: "Your results have been saved as a PNG." });
    } catch (err) {
      console.error("PNG export error:", err);
      toast({ title: "Export Failed", description: "Could not generate image.", variant: "destructive" });
    }
  };

  return (
    <Button variant="outline" size="sm" onClick={handleExport} className="flex items-center gap-2">
      <Image className="w-4 h-4" /> PNG
    </Button>
  );
}

export function ExportToCSVButton({ data, title }: { data: any[], title: string }) {
  const { toast } = useToast();

  const handleExport = () => {
    if (!data || !data.length) {
      toast({ title: "No Data", description: "There is no data to export." });
      return;
    }

    const headers = Object.keys(data[0]).join(",");
    const rows = data.map(row => Object.values(row).join(",")).join("\n");
    const csvContent = `data:text/csv;charset=utf-8,${headers}\n${rows}`;

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `${title.replace(/\s+/g, '-').toLowerCase()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <Button variant="outline" size="sm" onClick={handleExport} className="flex items-center gap-2">
      <Download className="w-4 h-4" /> CSV
    </Button>
  );
}

export function PrintResultsButton() {
  return (
    <Button variant="outline" size="sm" onClick={() => window.print()} className="flex items-center gap-2">
      <Printer className="w-4 h-4" /> Print
    </Button>
  );
}

export function ShareResultsButton() {
  const { toast } = useToast();

  const handleShare = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      toast({ title: "Link Copied", description: "You can now share your results with this link." });
    } catch {
      toast({ title: "Error", description: "Failed to copy link." });
    }
  };

  return (
    <Button variant="outline" size="sm" onClick={handleShare} className="flex items-center gap-2">
      <Share2 className="w-4 h-4" /> Share
    </Button>
  );
}
