import React, { useRef } from "react";
import { Button } from "@/components/ui/button";
import { Share2, Download, Link2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface ShareableInsightProps {
  title: string;
  results: { label: string; value: string; highlight?: boolean }[];
  calculatorSlug: string;
}

export function ShareableInsight({ title, results, calculatorSlug }: ShareableInsightProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const { toast } = useToast();

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      toast({ title: "Link Copied", description: "Share this link so others can use this calculator." });
    } catch {
      toast({ title: "Error", description: "Could not copy the link.", variant: "destructive" });
    }
  };

  const handleDownloadPNG = async () => {
    if (!cardRef.current) return;
    try {
      const html2canvas = (await import("html2canvas")).default;
      const canvas = await html2canvas(cardRef.current, {
        backgroundColor: "#ffffff",
        scale: 2,
        useCORS: true,
      });
      const link = document.createElement("a");
      link.download = `${calculatorSlug}-results.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
      toast({ title: "Image Downloaded", description: "Your results have been saved as an image." });
    } catch {
      toast({ title: "Export Failed", description: "Could not generate the image.", variant: "destructive" });
    }
  };

  if (results.length === 0) return null;

  return (
    <div className="mt-8 mb-6">
      <div ref={cardRef} className="bg-white border-2 border-teal-200 rounded-2xl p-6 md:p-8">
        <div className="flex items-center gap-2 mb-4">
          <div className="h-1.5 w-8 bg-teal-500 rounded-full" />
          <p className="text-xs uppercase tracking-wider font-bold text-teal-600">Your Results</p>
        </div>
        <h3 className="font-serif text-xl font-bold mb-5">{title}</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {results.map((r, i) => (
            <div
              key={i}
              className={`rounded-xl p-4 ${r.highlight ? "bg-teal-50 border border-teal-200" : "bg-gray-50 border border-gray-200"}`}
            >
              <p className="text-xs text-gray-500 uppercase tracking-wide mb-1">{r.label}</p>
              <p className={`text-xl font-bold ${r.highlight ? "text-teal-700" : "text-gray-900"}`}>{r.value}</p>
            </div>
          ))}
        </div>
        <p className="text-[10px] text-gray-400 mt-4">Generated by RealProfits.com</p>
      </div>

      <div className="flex gap-2 mt-4">
        <Button variant="outline" size="sm" onClick={handleCopyLink} className="flex items-center gap-2">
          <Link2 className="h-4 w-4" /> Copy Link to Results
        </Button>
        <Button variant="outline" size="sm" onClick={handleDownloadPNG} className="flex items-center gap-2">
          <Download className="h-4 w-4" /> Download as PNG
        </Button>
      </div>
    </div>
  );
}
